# **Creating NumPy Arrays**

In [ ]:
import numpy as np

# Creating a 1D array
array1 = np.array([1, 2, 3])
print(array1)  # Output: [1 2 3]

# Creating a 2D array
array2 = np.array([[1, 2], [3, 4]])
print(array2)
# Output:
# [[1 2]
#  [3 4]]

# Creating arrays with zeros, ones, or empty values
zeros_array = np.zeros((2, 3))
print(zeros_array)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]

ones_array = np.ones((2, 3))
print(ones_array)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]


[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


# **Array Properties**

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Shape of the array
print(array.shape)  # Output: (2, 3)

# Number of dimensions
print(array.ndim)  # Output: 2

# Total number of elements
print(array.size)  # Output: 6

# Data type of elements
print(array.dtype)  # Output: int32 (may vary depending on your system)


(2, 3)
2
6
int64


# **Accessing and Modifying Elements**

In [ ]:
array = np.array([[10, 20, 30], [40, 50, 60]])

# Accessing elements
print(array[0, 1])  # Output: 20 (row 0, column 1)

# Slicing
print(array[:, 1])  # Output: [20 50] (all rows, column 1)

# Modifying elements
array[1, 2] = 100
print(array)
# Output:
# [[ 10  20  30]
#  [ 40  50 100]]


20
[20 50]
[[ 10  20  30]
 [ 40  50 100]]


# **Mathematical Operations**

In [ ]:
array = np.array([1, 2, 3, 4])

# Element-wise operations
print(array + 10)  # Output: [11 12 13 14]
print(array * 2)   # Output: [2 4 6 8]

# Universal functions (ufuncs)
print(np.sqrt(array))  # Output: [1. 1.41421356 1.73205081 2. ]
print(np.sum(array))   # Output: 10
print(np.mean(array))  # Output: 2.5


[11 12 13 14]
[2 4 6 8]
[1.         1.41421356 1.73205081 2.        ]
10
2.5


# **Array Reshaping**

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to 2x3
reshaped_array = array.reshape((2, 3))
print(reshaped_array)
# Output:
# [[1 2 3]
#  [4 5 6]]


# **Stacking and Splitting Arrays**

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stacking vertically
vstacked = np.vstack((array1, array2))
print(vstacked)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Stacking horizontally
hstacked = np.hstack((array1, array2))
print(hstacked)  # Output: [1 2 3 4 5 6]


# **Array Broadcasting**

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

# Adding a scalar to all elements
print(array + scalar)
# Output:
# [[11 12 13]
#  [14 15 16]]


# **Filtering and Boolean Indexing**

In [ ]:
array = np.array([10, 20, 30, 40, 50])

# Filtering elements greater than 25
filtered = array[array > 25]
print(filtered)  # Output: [30 40 50]

# Boolean indexing
bool_index = array % 20 == 0
print(array[bool_index])  # Output: [20 40]


# **Random Number Generation**

In [ ]:
# Generate random numbers
random_array = np.random.rand(3, 2)  # 3x2 array of random values
print(random_array)

# Random integers
random_integers = np.random.randint(1, 10, size=(2, 3))
print(random_integers)


NameError: name 'np' is not defined

# **Linear Algebra Operations**

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(matrix1, matrix2)
print(result)
# Output:
# [[19 22]
#  [43 50]]

# Transpose of a matrix
transpose = np.transpose(matrix1)
print(transpose)
# Output:
# [[1 3]
#  [2 4]]


# **Saving and Loading Arrays**

In [ ]:
array = np.array([1, 2, 3, 4, 5])

# Save to a file
np.save("my_array.npy", array)

# Load from a file
loaded_array = np.load("my_array.npy")
print(loaded_array)  # Output: [1 2 3 4 5]


# **Sorting and Searching**

In [ ]:
array = np.array([3, 1, 4, 1, 5, 9])

# Sorting the array
sorted_array = np.sort(array)
print(sorted_array)  # Output: [1 1 3 4 5 9]

# Searching for an element
index = np.where(array == 4)
print(index)  # Output: (array([2]),) (index of 4)


# **Aggregation Functions**

In [ ]:
array = np.array([1, 2, 3, 4, 5])

# Minimum, maximum, and sum
print(np.min(array))  # Output: 1
print(np.max(array))  # Output: 5
print(np.sum(array))  # Output: 15

# Standard deviation and variance
print(np.std(array))  # Output: 1.4142135623730951
print(np.var(array))  # Output: 2.0


# **Handling Missing Data**

In [ ]:
array = np.array([1, np.nan, 3, 4])

# Checking for NaN values
print(np.isnan(array))  # Output: [False  True False False]

# Replacing NaN with a specific value
array[np.isnan(array)] = 0
print(array)  # Output: [1. 0. 3. 4.]
